name: Echo FOO Variable

on:
  push:
    branches:
      - main

jobs:
  echo-foo:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Echo FOO variable
        run: |
            echo "The value of FOO is: $FOO"


